# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/detail.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(425, 589)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 421, 601))
        self.label.setStyleSheet("QWidget {\n"
"    background: qlineargradient(\n"
"        spread:pad,\n"
"        x1:0, y1:0,   /* bắt đầu ở trên */\n"
"        x2:0, y2:1,   /* kéo xuống dưới */\n"
"        stop:0 #0f2027,   /* đen đậm trên cùng */\n"
"        stop:0.5 #203a43, /* xanh đậm ở giữa */\n"
"        stop:1 #2c5364    /* xanh teal ở dưới */\n"
"    );\n"
"}")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/black.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalSlider = QtWidgets.QSlider(parent=Form)
        self.horizontalSlider.setGeometry(QtCore.QRect(30, 330, 341, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(30, 450, 21, 21))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/volume-high-solid.svg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalSlider_2 = QtWidgets.QSlider(parent=Form)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(60, 450, 321, 22))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(130, 380, 41, 31))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/backward-solid.svg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(250, 380, 41, 31))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/forward-solid.svg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(200, 380, 21, 31))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/play-solid.svg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(30, 380, 31, 31))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/shuffle-solid.svg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setGeometry(QtCore.QRect(350, 380, 31, 31))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/heart-solid.svg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=Form)
        self.label_8.setGeometry(QtCore.QRect(30, 260, 411, 41))
        self.label_8.setStyleSheet("color: white;\n"
"font: 700 12pt \"Microsoft YaHei\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=Form)
        self.label_9.setGeometry(QtCore.QRect(30, 300, 131, 20))
        self.label_9.setStyleSheet("color: rgb(172, 172, 172)")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=Form)
        self.label_10.setGeometry(QtCore.QRect(100, 40, 221, 221))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/son tung.jpg"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=Form)
        self.label_11.setGeometry(QtCore.QRect(380, 10, 31, 31))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/spotify-brands (1).svg"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=Form)
        self.label_12.setGeometry(QtCore.QRect(30, 350, 63, 20))
        self.label_12.setStyleSheet("color:white")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(parent=Form)
        self.label_13.setGeometry(QtCore.QRect(350, 350, 63, 20))
        self.label_13.setStyleSheet("color:white")
        self.label_13.setObjectName("label_13")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(30, 520, 361, 51))
        self.pushButton.setStyleSheet(" background-color: white;\n"
"    color: black;\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    font-size: 20px;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_14 = QtWidgets.QLabel(parent=Form)
        self.label_14.setGeometry(QtCore.QRect(140, -10, 151, 61))
        self.label_14.setStyleSheet("color: white;\n"
"font: 700 12pt \"Microsoft YaHei\";")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(parent=Form)
        self.label_15.setGeometry(QtCore.QRect(0, 0, 51, 51))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/angle-down-solid-full.svg"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_8.setText(_translate("Form", "Đừng Làm Trái Tim Anh Đau"))
        self.label_9.setText(_translate("Form", "SƠN TÙNG M-TP "))
        self.label_12.setText(_translate("Form", "0:00"))
        self.label_13.setText(_translate("Form", "5:26"))
        self.pushButton.setText(_translate("Form", "Behind The Lyrics"))
        self.label_14.setText(_translate("Form", "Random Song"))
