# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/home.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1080, 720)
        Form.setStyleSheet("background-color:rgb(79,79,79)")
        self.horizontalSlider = QtWidgets.QSlider(parent=Form)
        self.horizontalSlider.setGeometry(QtCore.QRect(350, 680, 431, 22))
        self.horizontalSlider.setStyleSheet("background-color: transparent")
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=Form)
        self.stackedWidget.setGeometry(QtCore.QRect(140, 60, 941, 531))
        self.stackedWidget.setStyleSheet("background-color:rgb(79, 79, 79)")
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.label_4 = QtWidgets.QLabel(parent=self.home)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 321, 61))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(-1)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:white;\n"
"font-size: 45px;\n"
"font-weight: bold;\n"
" etter-spacing: 0.5px;\n"
"background:transparent\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.home)
        self.label_5.setGeometry(QtCore.QRect(20, 120, 81, 91))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/z6498815129163_52317030fda41617c77e971ac6f6aace.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.listWidget = QtWidgets.QListWidget(parent=self.home)
        self.listWidget.setGeometry(QtCore.QRect(20, 120, 221, 91))
        self.listWidget.setStyleSheet("background-color:rgb(99, 99, 99);\n"
"padding: 10px;\n"
"border-radius:10px\n"
"")
        self.listWidget.setObjectName("listWidget")
        self.label_6 = QtWidgets.QLabel(parent=self.home)
        self.label_6.setGeometry(QtCore.QRect(110, 150, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(-1)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font-weight: bold;\n"
"  etter-spacing: 0.5px;\n"
"color:rgb(255, 255, 255);\n"
"font-size: 18px;\n"
"background-color:rgb(99,99,99)")
        self.label_6.setObjectName("label_6")
        self.listWidget_2 = QtWidgets.QListWidget(parent=self.home)
        self.listWidget_2.setGeometry(QtCore.QRect(280, 120, 291, 91))
        self.listWidget_2.setStyleSheet("background-color:rgb(99, 99, 99);\n"
"padding: 10px;\n"
"border-radius:10px\n"
"")
        self.listWidget_2.setObjectName("listWidget_2")
        self.label_7 = QtWidgets.QLabel(parent=self.home)
        self.label_7.setGeometry(QtCore.QRect(280, 120, 91, 91))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/z6498832574348_16983d2b2cb3fb4741b1091fefff519d.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.home)
        self.label_8.setGeometry(QtCore.QRect(390, 150, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(-1)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("font-weight: bold;\n"
"  etter-spacing: 0.5px;\n"
"color:rgb(255, 255, 255);\n"
"font-size: 18px;\n"
"background-color:rgb(99,99,99)")
        self.label_8.setObjectName("label_8")
        self.listWidget_3 = QtWidgets.QListWidget(parent=self.home)
        self.listWidget_3.setGeometry(QtCore.QRect(620, 120, 241, 91))
        self.listWidget_3.setStyleSheet("background-color:rgb(99, 99, 99);\n"
"padding: 10px;\n"
"border-radius:10px\n"
"")
        self.listWidget_3.setObjectName("listWidget_3")
        self.label_9 = QtWidgets.QLabel(parent=self.home)
        self.label_9.setGeometry(QtCore.QRect(620, 120, 91, 91))
        self.label_9.setStyleSheet("")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/z6498843329317_d5f9a2982984e39be71fa63c56255d28.jpg"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.home)
        self.label_10.setGeometry(QtCore.QRect(730, 150, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(-1)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("font-weight: bold;\n"
"  etter-spacing: 0.5px;\n"
"color:rgb(255, 255, 255);\n"
"font-size: 18px;\n"
"background-color:rgb(99,99,99)")
        self.label_10.setObjectName("label_10")
        self.listWidget_4 = QtWidgets.QListWidget(parent=self.home)
        self.listWidget_4.setGeometry(QtCore.QRect(20, 270, 221, 91))
        self.listWidget_4.setStyleSheet("background-color:rgb(99, 99, 99);\n"
"padding: 10px;\n"
"border-radius:10px\n"
"")
        self.listWidget_4.setObjectName("listWidget_4")
        self.label_11 = QtWidgets.QLabel(parent=self.home)
        self.label_11.setGeometry(QtCore.QRect(20, 270, 81, 91))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/z6498855803386_3a41d86ed3e261a2cff390b13dae6e42.jpg"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.home)
        self.label_12.setGeometry(QtCore.QRect(140, 300, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(-1)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("font-weight: bold;\n"
"  etter-spacing: 0.5px;\n"
"color:rgb(255, 255, 255);\n"
"font-size: 18px;\n"
"background-color:rgb(99,99,99)")
        self.label_12.setObjectName("label_12")
        self.listWidget_5 = QtWidgets.QListWidget(parent=self.home)
        self.listWidget_5.setGeometry(QtCore.QRect(280, 270, 291, 91))
        self.listWidget_5.setStyleSheet("background-color:rgb(99, 99, 99);\n"
"padding: 10px;\n"
"border-radius:10px\n"
"")
        self.listWidget_5.setObjectName("listWidget_5")
        self.label_13 = QtWidgets.QLabel(parent=self.home)
        self.label_13.setGeometry(QtCore.QRect(280, 270, 91, 91))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/z6498876897954_59ddeff9bd8129a9120778cdb6c89686.jpg"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(parent=self.home)
        self.label_14.setGeometry(QtCore.QRect(380, 290, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(-1)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("font-weight: bold;\n"
"  etter-spacing: 0.5px;\n"
"color:rgb(255, 255, 255);\n"
"font-size: 18px;\n"
"background-color:rgb(99,99,99)\n"
"\n"
"")
        self.label_14.setObjectName("label_14")
        self.listWidget_6 = QtWidgets.QListWidget(parent=self.home)
        self.listWidget_6.setGeometry(QtCore.QRect(620, 270, 241, 91))
        self.listWidget_6.setStyleSheet("background-color:rgb(99, 99, 99);\n"
"padding: 10px;\n"
"border-radius:10px\n"
"")
        self.listWidget_6.setObjectName("listWidget_6")
        self.label_15 = QtWidgets.QLabel(parent=self.home)
        self.label_15.setGeometry(QtCore.QRect(620, 270, 91, 91))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/z6498882588427_34e9891f52d595a569a46ffdaf578fbe.jpg"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(parent=self.home)
        self.label_16.setGeometry(QtCore.QRect(740, 300, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(-1)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("font-weight: bold;\n"
"  etter-spacing: 0.5px;\n"
"color:rgb(255, 255, 255);\n"
"font-size: 18px;\n"
"background-color:rgb(99,99,99)")
        self.label_16.setObjectName("label_16")
        self.label_62 = QtWidgets.QLabel(parent=self.home)
        self.label_62.setGeometry(QtCore.QRect(300, 110, 241, 251))
        self.label_62.setStyleSheet("background:transparent")
        self.label_62.setText("")
        self.label_62.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/spotify-brands.svg"))
        self.label_62.setScaledContents(True)
        self.label_62.setObjectName("label_62")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.home)
        self.lineEdit.setGeometry(QtCore.QRect(340, 40, 321, 51))
        self.lineEdit.setStyleSheet(" border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    padding: 10px 16px;\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    font-size: 25px;")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(parent=self.home)
        self.label_3.setGeometry(QtCore.QRect(610, 50, 21, 21))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/magnifying-glass-solid.svg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_62.raise_()
        self.listWidget.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.listWidget_2.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.listWidget_3.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.listWidget_4.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.listWidget_5.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.listWidget_6.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.lineEdit.raise_()
        self.label_3.raise_()
        self.stackedWidget.addWidget(self.home)
        self.profile = QtWidgets.QWidget()
        self.profile.setObjectName("profile")
        self.label_20 = QtWidgets.QLabel(parent=self.profile)
        self.label_20.setGeometry(QtCore.QRect(70, 100, 131, 51))
        self.label_20.setStyleSheet("   color: white;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 0.5px;\n"
"background-color: transparent")
        self.label_20.setObjectName("label_20")
        self.txt_name = QtWidgets.QLineEdit(parent=self.profile)
        self.txt_name.setGeometry(QtCore.QRect(60, 160, 281, 41))
        self.txt_name.setStyleSheet(" border: 2px solid white;\n"
" border-radius: 20px;\n"
" padding: 10px 16px;\n"
"background-color: transparent;\n"
" color: white;\n"
"    font-size: 14px;")
        self.txt_name.setObjectName("txt_name")
        self.label_21 = QtWidgets.QLabel(parent=self.profile)
        self.label_21.setGeometry(QtCore.QRect(70, 230, 131, 51))
        self.label_21.setStyleSheet("   color: white;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 0.5px;\n"
"background-color: transparent")
        self.label_21.setObjectName("label_21")
        self.txt_email = QtWidgets.QLineEdit(parent=self.profile)
        self.txt_email.setGeometry(QtCore.QRect(60, 300, 281, 41))
        self.txt_email.setStyleSheet(" border: 2px solid white;\n"
" border-radius: 20px;\n"
" padding: 10px 16px;\n"
"background-color: transparent;\n"
" color: white;\n"
"    font-size: 14px;")
        self.txt_email.setObjectName("txt_email")
        self.label_19 = QtWidgets.QLabel(parent=self.profile)
        self.label_19.setGeometry(QtCore.QRect(620, 230, 131, 51))
        self.label_19.setStyleSheet(" color: white;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 0.5px;\n"
"background-color: transparent")
        self.label_19.setObjectName("label_19")
        self.btn_avatar = QtWidgets.QPushButton(parent=self.profile)
        self.btn_avatar.setGeometry(QtCore.QRect(400, 20, 131, 111))
        self.btn_avatar.setStyleSheet("background:none;\n"
"border:none;\n"
"")
        self.btn_avatar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/circle-user-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_avatar.setIcon(icon)
        self.btn_avatar.setIconSize(QtCore.QSize(100, 100))
        self.btn_avatar.setObjectName("btn_avatar")
        self.label_18 = QtWidgets.QLabel(parent=self.profile)
        self.label_18.setGeometry(QtCore.QRect(620, 300, 161, 51))
        self.label_18.setStyleSheet(" color: white;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 0.5px;\n"
"background-color: transparent\n"
"")
        self.label_18.setObjectName("label_18")
        self.txt_birthday = QtWidgets.QDateEdit(parent=self.profile)
        self.txt_birthday.setGeometry(QtCore.QRect(800, 320, 110, 26))
        self.txt_birthday.setStyleSheet("color:rgb(255, 255, 255)")
        self.txt_birthday.setObjectName("txt_birthday")
        self.btn_save_account = QtWidgets.QPushButton(parent=self.profile)
        self.btn_save_account.setGeometry(QtCore.QRect(370, 420, 191, 51))
        self.btn_save_account.setStyleSheet(" background-color: white;\n"
"    color: black;\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    font-size: 20px;")
        self.btn_save_account.setObjectName("btn_save_account")
        self.label_60 = QtWidgets.QLabel(parent=self.profile)
        self.label_60.setGeometry(QtCore.QRect(370, 160, 191, 201))
        self.label_60.setStyleSheet("background-color: transparent")
        self.label_60.setText("")
        self.label_60.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/spotify-brands.svg"))
        self.label_60.setScaledContents(True)
        self.label_60.setObjectName("label_60")
        self.txt_gender = QtWidgets.QComboBox(parent=self.profile)
        self.txt_gender.setGeometry(QtCore.QRect(750, 250, 76, 26))
        self.txt_gender.setObjectName("txt_gender")
        self.txt_gender.addItem("")
        self.txt_gender.addItem("")
        self.txt_gender.addItem("")
        self.txt_gender.addItem("")
        self.stackedWidget.addWidget(self.profile)
        self.playlist = QtWidgets.QWidget()
        self.playlist.setObjectName("playlist")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.playlist)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 30, 93, 29))
        self.pushButton_6.setStyleSheet("font-weight: bold;\n"
"etter-spacing: 0.5px;\n"
"color:rgb(255, 255, 255);\n"
"font-size: 18px;\n"
"background:none;\n"
"border:none")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.playlist)
        self.pushButton_7.setGeometry(QtCore.QRect(340, 140, 111, 61))
        self.pushButton_7.setStyleSheet("background:none;\n"
"border:none")
        self.pushButton_7.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/circle-regular.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_7.setIcon(icon1)
        self.pushButton_7.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.playlist)
        self.pushButton_8.setGeometry(QtCore.QRect(340, 290, 111, 61))
        self.pushButton_8.setStyleSheet("background:none;\n"
"border:none")
        self.pushButton_8.setText("")
        self.pushButton_8.setIcon(icon1)
        self.pushButton_8.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_8.setObjectName("pushButton_8")
        self.frame = QtWidgets.QFrame(parent=self.playlist)
        self.frame.setGeometry(QtCore.QRect(-10, 110, 431, 131))
        self.frame.setStyleSheet("padding: 10px;\n"
"border-radius:10px")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(0, -10, 141, 151))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/z6565114390107_1053d1259e768448bbed37d712417041.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_17 = QtWidgets.QLabel(parent=self.frame)
        self.label_17.setGeometry(QtCore.QRect(140, 40, 241, 51))
        self.label_17.setStyleSheet("etter-spacing: 0.5px;\n"
"color:rgb(255, 255, 255);\n"
"font-size: 18px;")
        self.label_17.setObjectName("label_17")
        self.frame_2 = QtWidgets.QFrame(parent=self.playlist)
        self.frame_2.setGeometry(QtCore.QRect(490, 110, 431, 131))
        self.frame_2.setStyleSheet("padding: 10px;\n"
"border-radius:10px;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_26 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_26.setGeometry(QtCore.QRect(-10, -10, 141, 151))
        self.label_26.setStyleSheet("")
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/z6565170373515_ba2aeac2b06b9103f36f7c72b0168d5e.jpg"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_27.setGeometry(QtCore.QRect(140, 50, 201, 41))
        self.label_27.setStyleSheet("etter-spacing: 0.5px;\n"
"color:rgb(255, 255, 255);\n"
"font-size: 18px;")
        self.label_27.setObjectName("label_27")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_9.setGeometry(QtCore.QRect(340, 30, 111, 61))
        self.pushButton_9.setStyleSheet("background:none;\n"
"border:none")
        self.pushButton_9.setText("")
        self.pushButton_9.setIcon(icon1)
        self.pushButton_9.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_9.setObjectName("pushButton_9")
        self.frame_3 = QtWidgets.QFrame(parent=self.playlist)
        self.frame_3.setGeometry(QtCore.QRect(490, 260, 431, 131))
        self.frame_3.setStyleSheet("padding: 10px;\n"
"border-radius:10px")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_30 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_30.setGeometry(QtCore.QRect(-10, -10, 141, 151))
        self.label_30.setStyleSheet("")
        self.label_30.setText("")
        self.label_30.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/z6565175587746_eb8f98ae579a50c9db81346956f12136.jpg"))
        self.label_30.setScaledContents(True)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_31.setGeometry(QtCore.QRect(130, 40, 201, 41))
        self.label_31.setStyleSheet("etter-spacing: 0.5px;\n"
"color:rgb(255, 255, 255);\n"
"font-size: 18px;")
        self.label_31.setObjectName("label_31")
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton_11.setGeometry(QtCore.QRect(340, 30, 111, 61))
        self.pushButton_11.setStyleSheet("background:none;\n"
"border:none")
        self.pushButton_11.setText("")
        self.pushButton_11.setIcon(icon1)
        self.pushButton_11.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_11.setObjectName("pushButton_11")
        self.frame_4 = QtWidgets.QFrame(parent=self.playlist)
        self.frame_4.setGeometry(QtCore.QRect(0, 270, 421, 131))
        self.frame_4.setStyleSheet("padding: 10px;\n"
"border-radius:10px")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_22 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_22.setGeometry(QtCore.QRect(-10, -10, 141, 151))
        self.label_22.setStyleSheet("")
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/z6565142229589_4d2c9fcab1852a83f9480390dd317c4e.jpg"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_23.setGeometry(QtCore.QRect(140, 40, 201, 41))
        self.label_23.setStyleSheet("etter-spacing: 0.5px;\n"
"color:rgb(255, 255, 255);\n"
"font-size: 18px;")
        self.label_23.setObjectName("label_23")
        self.label_61 = QtWidgets.QLabel(parent=self.playlist)
        self.label_61.setGeometry(QtCore.QRect(320, 110, 241, 261))
        self.label_61.setStyleSheet("background:transparent")
        self.label_61.setText("")
        self.label_61.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/spotify-brands.svg"))
        self.label_61.setScaledContents(True)
        self.label_61.setObjectName("label_61")
        self.label_2 = QtWidgets.QLabel(parent=self.playlist)
        self.label_2.setGeometry(QtCore.QRect(380, 60, 221, 31))
        self.label_2.setStyleSheet("font-weight: bold;\n"
"etter-spacing: 0.5px;\n"
"color:rgb(255, 255, 255);\n"
"font-size: 26px;\n"
"background:none;\n"
"border:none")
        self.label_2.setObjectName("label_2")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.playlist)
        self.lineEdit_5.setGeometry(QtCore.QRect(550, 40, 321, 51))
        self.lineEdit_5.setStyleSheet(" border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    padding: 10px 16px;\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    font-size: 25px;")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_25 = QtWidgets.QLabel(parent=self.playlist)
        self.label_25.setGeometry(QtCore.QRect(830, 50, 21, 21))
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/magnifying-glass-solid.svg"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.label_61.raise_()
        self.frame_4.raise_()
        self.frame.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.label_2.raise_()
        self.lineEdit_5.raise_()
        self.label_25.raise_()
        self.stackedWidget.addWidget(self.playlist)
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(530, 620, 91, 51))
        self.pushButton.setStyleSheet("border: none;\n"
"background: none")
        self.pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/play-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setObjectName("pushButton")
        self.btn_home = QtWidgets.QPushButton(parent=Form)
        self.btn_home.setGeometry(QtCore.QRect(150, 0, 131, 61))
        self.btn_home.setStyleSheet("background:none;\n"
"border:none;\n"
"font-weight: bold;\n"
"etter-spacing: 0.5px;\n"
"color:rgb(255, 255, 255);\n"
"font-size: 25px;\n"
"\n"
"\n"
"\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/house-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_home.setIcon(icon3)
        self.btn_home.setObjectName("btn_home")
        self.btn_profile = QtWidgets.QPushButton(parent=Form)
        self.btn_profile.setGeometry(QtCore.QRect(940, 0, 131, 51))
        self.btn_profile.setStyleSheet(" background-color: white;\n"
"    color: black;\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    font-size: 20px;")
        self.btn_profile.setObjectName("btn_profile")
        self.pushButton_14 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_14.setGeometry(QtCore.QRect(10, 70, 93, 29))
        self.pushButton_14.setStyleSheet("font-weight: bold;\n"
"etter-spacing: 0.5px;\n"
"color:rgb(255, 255, 255);\n"
"font-size: 18px;\n"
"background:none;\n"
"border:none;\n"
"background-color: transparent")
        self.pushButton_14.setObjectName("pushButton_14")
        self.btn_playlist = QtWidgets.QPushButton(parent=Form)
        self.btn_playlist.setGeometry(QtCore.QRect(0, 110, 51, 29))
        self.btn_playlist.setStyleSheet("background:none;\n"
"border:none\n"
"")
        self.btn_playlist.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/plus-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_playlist.setIcon(icon4)
        self.btn_playlist.setIconSize(QtCore.QSize(30, 30))
        self.btn_playlist.setObjectName("btn_playlist")
        self.label_24 = QtWidgets.QLabel(parent=Form)
        self.label_24.setGeometry(QtCore.QRect(40, 120, 101, 20))
        self.label_24.setStyleSheet("color:rgb(255, 255, 255);\n"
"background-color: transparent")
        self.label_24.setObjectName("label_24")
        self.btn_favorite = QtWidgets.QPushButton(parent=Form)
        self.btn_favorite.setGeometry(QtCore.QRect(-20, 160, 93, 29))
        self.btn_favorite.setStyleSheet("background:none;\n"
"border:none\n"
"")
        self.btn_favorite.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/heart-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_favorite.setIcon(icon5)
        self.btn_favorite.setIconSize(QtCore.QSize(30, 30))
        self.btn_favorite.setObjectName("btn_favorite")
        self.label_32 = QtWidgets.QLabel(parent=Form)
        self.label_32.setGeometry(QtCore.QRect(50, 170, 81, 20))
        self.label_32.setStyleSheet("color:rgb(255,255,255);\n"
"background-color: transparent")
        self.label_32.setObjectName("label_32")
        self.pushButton_17 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_17.setGeometry(QtCore.QRect(720, 620, 91, 51))
        self.pushButton_17.setStyleSheet("border: none;\n"
"background: none")
        self.pushButton_17.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/volume-high-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_17.setIcon(icon6)
        self.pushButton_17.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalSlider_2 = QtWidgets.QSlider(parent=Form)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(800, 630, 141, 22))
        self.horizontalSlider_2.setStyleSheet("background-color: transparent")
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.pushButton_18 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_18.setGeometry(QtCore.QRect(620, 620, 91, 51))
        self.pushButton_18.setStyleSheet("border: none;\n"
"background: none")
        self.pushButton_18.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/forward-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_18.setIcon(icon7)
        self.pushButton_18.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_19.setGeometry(QtCore.QRect(440, 620, 91, 51))
        self.pushButton_19.setStyleSheet("border: none;\n"
"background: none")
        self.pushButton_19.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/backward-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_19.setIcon(icon8)
        self.pushButton_19.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_19.setObjectName("pushButton_19")
        self.label_29 = QtWidgets.QLabel(parent=Form)
        self.label_29.setGeometry(QtCore.QRect(10, 640, 81, 71))
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/z6588244063627_74df258950c533ffb1a252c12d4ad801.jpg"))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.label_33 = QtWidgets.QLabel(parent=Form)
        self.label_33.setGeometry(QtCore.QRect(100, 660, 201, 31))
        self.label_33.setStyleSheet("etter-spacing: 0.5px;\n"
"color:rgb(255, 255, 255);\n"
"font-size: 18px;\n"
"background-color: transparent")
        self.label_33.setObjectName("label_33")
        self.pushButton_21 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_21.setGeometry(QtCore.QRect(170, 660, 93, 29))
        self.pushButton_21.setStyleSheet("background:none;\n"
"border:none;\n"
"background-color: transparent\n"
"")
        self.pushButton_21.setText("")
        self.pushButton_21.setIcon(icon5)
        self.pushButton_21.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_21.setObjectName("pushButton_21")
        self.label_34 = QtWidgets.QLabel(parent=Form)
        self.label_34.setGeometry(QtCore.QRect(10, 10, 121, 51))
        self.label_34.setStyleSheet("background-color: transparent")
        self.label_34.setText("")
        self.label_34.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/z6588263446916_7cb113bb0fdf10c8d89150d39c6c91a4-removebg-preview.png"))
        self.label_34.setScaledContents(True)
        self.label_34.setObjectName("label_34")
        self.pushButton_22 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_22.setGeometry(QtCore.QRect(350, 620, 91, 51))
        self.pushButton_22.setStyleSheet("border: none;\n"
"background: none")
        self.pushButton_22.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/shuffle-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_22.setIcon(icon9)
        self.pushButton_22.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_22.setObjectName("pushButton_22")
        self.label_35 = QtWidgets.QLabel(parent=Form)
        self.label_35.setGeometry(QtCore.QRect(320, 680, 31, 20))
        self.label_35.setStyleSheet("color:rgb(255,255,255);\n"
"background-color: transparent")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(parent=Form)
        self.label_36.setGeometry(QtCore.QRect(790, 680, 63, 20))
        self.label_36.setStyleSheet("color:rgb(255,255,255);\n"
"background-color: transparent")
        self.label_36.setObjectName("label_36")
        self.stackedWidget.raise_()
        self.btn_home.raise_()
        self.pushButton.raise_()
        self.horizontalSlider.raise_()
        self.btn_profile.raise_()
        self.pushButton_14.raise_()
        self.btn_playlist.raise_()
        self.label_24.raise_()
        self.btn_favorite.raise_()
        self.label_32.raise_()
        self.pushButton_17.raise_()
        self.horizontalSlider_2.raise_()
        self.pushButton_18.raise_()
        self.pushButton_19.raise_()
        self.label_29.raise_()
        self.label_33.raise_()
        self.pushButton_21.raise_()
        self.label_34.raise_()
        self.pushButton_22.raise_()
        self.label_35.raise_()
        self.label_36.raise_()

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Good Afternoon"))
        self.label_6.setText(_translate("Form", "The Spectre"))
        self.label_8.setText(_translate("Form", "Die With A Smile"))
        self.label_10.setText(_translate("Form", "Daylight"))
        self.label_12.setText(_translate("Form", "APT"))
        self.label_14.setText(_translate("Form", "Legends Never Die"))
        self.label_16.setText(_translate("Form", "Faded"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Search"))
        self.label_20.setText(_translate("Form", "Username:"))
        self.txt_name.setPlaceholderText(_translate("Form", "Username:"))
        self.label_21.setText(_translate("Form", "Email:"))
        self.txt_email.setPlaceholderText(_translate("Form", "Email:"))
        self.label_19.setText(_translate("Form", "Gender:"))
        self.label_18.setText(_translate("Form", "Date And Birth:"))
        self.btn_save_account.setText(_translate("Form", "Save Account"))
        self.txt_gender.setItemText(0, _translate("Form", "None"))
        self.txt_gender.setItemText(1, _translate("Form", "Male"))
        self.txt_gender.setItemText(2, _translate("Form", "Female"))
        self.txt_gender.setItemText(3, _translate("Form", "Other"))
        self.pushButton_6.setText(_translate("Form", "Playlist:"))
        self.label_17.setText(_translate("Form", "Em Của Ngày Hôm Qua"))
        self.label_27.setText(_translate("Form", "Bắc Bling"))
        self.label_31.setText(_translate("Form", "Tái Sinh"))
        self.label_23.setText(_translate("Form", "Mất Kết Nối"))
        self.label_2.setText(_translate("Form", "My Playlist"))
        self.lineEdit_5.setPlaceholderText(_translate("Form", "Search"))
        self.btn_home.setText(_translate("Form", "  Home"))
        self.btn_profile.setText(_translate("Form", "Profile"))
        self.pushButton_14.setText(_translate("Form", "Playlist:"))
        self.label_24.setText(_translate("Form", "Create Playlist"))
        self.label_32.setText(_translate("Form", "Liked Songs"))
        self.label_33.setText(_translate("Form", "Phép Màu"))
        self.label_35.setText(_translate("Form", "0:00"))
        self.label_36.setText(_translate("Form", "4:21"))

