# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/register.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 600)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 1001, 601))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/Spotify HD Wallpaper Teahub Io.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(parent=Form)
        self.listWidget.setGeometry(QtCore.QRect(340, 20, 371, 551))
        self.listWidget.setStyleSheet("background-color:rgb(138, 138, 138);\n"
"padding: 10px;\n"
"border-radius: 10px;")
        self.listWidget.setObjectName("listWidget")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(470, 20, 111, 61))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/img/565210f00d0debfe7ebe356cabfcfdd7.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.txt_name = QtWidgets.QLineEdit(parent=Form)
        self.txt_name.setGeometry(QtCore.QRect(360, 140, 311, 41))
        self.txt_name.setStyleSheet(" border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    padding: 10px 16px;\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    font-size: 14px;")
        self.txt_name.setObjectName("txt_name")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(370, 110, 141, 20))
        self.label_3.setStyleSheet("   color: white;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 0.5px;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(470, 70, 171, 41))
        self.label_4.setStyleSheet("   color: white;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 0.5px;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(370, 180, 141, 31))
        self.label_5.setStyleSheet("   color: white;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 0.5px;")
        self.label_5.setObjectName("label_5")
        self.txt_email = QtWidgets.QLineEdit(parent=Form)
        self.txt_email.setGeometry(QtCore.QRect(360, 210, 311, 41))
        self.txt_email.setStyleSheet(" border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    padding: 10px 16px;\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    font-size: 14px;")
        self.txt_email.setObjectName("txt_email")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(370, 250, 141, 31))
        self.label_6.setStyleSheet("   color: white;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 0.5px;")
        self.label_6.setObjectName("label_6")
        self.txt_password = QtWidgets.QLineEdit(parent=Form)
        self.txt_password.setGeometry(QtCore.QRect(360, 280, 311, 41))
        self.txt_password.setStyleSheet(" border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    padding: 10px 16px;\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    font-size: 14px;")
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_password.setObjectName("txt_password")
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setGeometry(QtCore.QRect(360, 320, 201, 31))
        self.label_7.setStyleSheet("   color: white;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 0.5px;")
        self.label_7.setObjectName("label_7")
        self.txt_confirm_password = QtWidgets.QLineEdit(parent=Form)
        self.txt_confirm_password.setGeometry(QtCore.QRect(360, 360, 311, 41))
        self.txt_confirm_password.setStyleSheet(" border: 2px solid white;\n"
"    border-radius: 20px;\n"
"    padding: 10px 16px;\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    font-size: 14px;")
        self.txt_confirm_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_confirm_password.setObjectName("txt_confirm_password")
        self.btn_register = QtWidgets.QPushButton(parent=Form)
        self.btn_register.setGeometry(QtCore.QRect(370, 460, 321, 51))
        self.btn_register.setStyleSheet(" background-color: white;\n"
"    color: black;\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    padding: 10px;\n"
"    font-weight: bold;")
        self.btn_register.setObjectName("btn_register")
        self.label_8 = QtWidgets.QLabel(parent=Form)
        self.label_8.setGeometry(QtCore.QRect(630, 290, 31, 20))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/img/eye-slash-solid.svg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=Form)
        self.label_9.setGeometry(QtCore.QRect(630, 370, 31, 20))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/img/eye-slash-solid.svg"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.checkBox = QtWidgets.QCheckBox(parent=Form)
        self.checkBox.setGeometry(QtCore.QRect(350, 410, 351, 41))
        self.checkBox.setObjectName("checkBox")
        self.label_10 = QtWidgets.QLabel(parent=Form)
        self.label_10.setGeometry(QtCore.QRect(360, 520, 261, 41))
        self.label_10.setStyleSheet("   color: white;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 0.5px;")
        self.label_10.setObjectName("label_10")
        self.btn_login = QtWidgets.QPushButton(parent=Form)
        self.btn_login.setGeometry(QtCore.QRect(600, 520, 91, 41))
        self.btn_login.setStyleSheet(" background-color: white;\n"
"    color: black;\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    padding: 10px;\n"
"    font-weight: bold;")
        self.btn_login.setObjectName("btn_login")
        self.btn_eye_p = QtWidgets.QPushButton(parent=Form)
        self.btn_eye_p.setGeometry(QtCore.QRect(590, 290, 93, 29))
        self.btn_eye_p.setStyleSheet("border:none;\n"
"background:none;")
        self.btn_eye_p.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/../img/eye-slash-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_eye_p.setIcon(icon)
        self.btn_eye_p.setObjectName("btn_eye_p")
        self.btn_eye_cp = QtWidgets.QPushButton(parent=Form)
        self.btn_eye_cp.setGeometry(QtCore.QRect(590, 370, 93, 29))
        self.btn_eye_cp.setStyleSheet("border:none;\n"
"background:none;")
        self.btn_eye_cp.setText("")
        self.btn_eye_cp.setIcon(icon)
        self.btn_eye_cp.setObjectName("btn_eye_cp")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.txt_name.setPlaceholderText(_translate("Form", "Username:"))
        self.label_3.setText(_translate("Form", "Username:"))
        self.label_4.setText(_translate("Form", "Sign Up"))
        self.label_5.setText(_translate("Form", "Email:"))
        self.txt_email.setPlaceholderText(_translate("Form", "Email:"))
        self.label_6.setText(_translate("Form", "Password:"))
        self.txt_password.setPlaceholderText(_translate("Form", "Password:"))
        self.label_7.setText(_translate("Form", " Confirm Password:"))
        self.txt_confirm_password.setPlaceholderText(_translate("Form", "Confirm Password:"))
        self.btn_register.setText(_translate("Form", "Sign Up"))
        self.checkBox.setText(_translate("Form", "I agree to Spotify\' s Terms and Conditions of Use\n"
" and Privacy Policy"))
        self.label_10.setText(_translate("Form", "Already have an account?"))
        self.btn_login.setText(_translate("Form", "Login"))
