# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/song_item.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SongItem(object):
    def setupUi(self, SongItem):
        SongItem.setObjectName("SongItem")
        SongItem.resize(400, 80)
        self.horizontalLayout = QtWidgets.QHBoxLayout(SongItem)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_image = QtWidgets.QLabel(parent=SongItem)
        self.lbl_image.setMinimumSize(QtCore.QSize(60, 60))
        self.lbl_image.setMaximumSize(QtCore.QSize(60, 60))
        self.lbl_image.setText("")
        self.lbl_image.setScaledContents(True)
        self.lbl_image.setObjectName("lbl_image")
        self.horizontalLayout.addWidget(self.lbl_image)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_name = QtWidgets.QLabel(parent=SongItem)
        self.lbl_name.setObjectName("lbl_name")
        self.verticalLayout.addWidget(self.lbl_name)
        self.lbl_artist = QtWidgets.QLabel(parent=SongItem)
        self.lbl_artist.setObjectName("lbl_artist")
        self.verticalLayout.addWidget(self.lbl_artist)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.btn_play = QtWidgets.QPushButton(parent=SongItem)
        self.btn_play.setMinimumSize(QtCore.QSize(60, 40))
        self.btn_play.setObjectName("btn_play")
        self.horizontalLayout.addWidget(self.btn_play)
        self.btn_add = QtWidgets.QPushButton(parent=SongItem)
        self.btn_add.setMinimumSize(QtCore.QSize(60, 40))
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout.addWidget(self.btn_add)

        self.retranslateUi(SongItem)
        QtCore.QMetaObject.connectSlotsByName(SongItem)

    def retranslateUi(self, SongItem):
        _translate = QtCore.QCoreApplication.translate
        SongItem.setWindowTitle(_translate("SongItem", "Song Item"))
        self.lbl_name.setText(_translate("SongItem", "Song Name"))
        self.lbl_artist.setText(_translate("SongItem", "Artist"))
        self.btn_play.setText(_translate("SongItem", "Play"))
        self.btn_add.setText(_translate("SongItem", "Add"))
