# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA09/NguyenKhoi/python-app/ui/song_item.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SongItem(object):
    def setupUi(self, SongItem):
        SongItem.setObjectName("SongItem")
        SongItem.resize(400, 83)
        self.horizontalLayout = QtWidgets.QHBoxLayout(SongItem)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_image = QtWidgets.QLabel(parent=SongItem)
        self.lbl_image.setMinimumSize(QtCore.QSize(60, 60))
        self.lbl_image.setMaximumSize(QtCore.QSize(60, 60))
        self.lbl_image.setText("")
        self.lbl_image.setScaledContents(True)
        self.lbl_image.setObjectName("lbl_image")
        self.horizontalLayout.addWidget(self.lbl_image)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_name = QtWidgets.QLabel(parent=SongItem)
        self.lbl_name.setStyleSheet("color:rgb(255,255,255);\n"
"background-color: transparent;\n"
"font-size: 20px;\n"
"font-weight: bold")
        self.lbl_name.setObjectName("lbl_name")
        self.verticalLayout.addWidget(self.lbl_name)
        self.lbl_artist = QtWidgets.QLabel(parent=SongItem)
        self.lbl_artist.setStyleSheet("color:rgb(189, 189, 189);\n"
"background-color: transparent;\n"
"font-size: 20px;")
        self.lbl_artist.setObjectName("lbl_artist")
        self.verticalLayout.addWidget(self.lbl_artist)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.btn_play = QtWidgets.QPushButton(parent=SongItem)
        self.btn_play.setMinimumSize(QtCore.QSize(60, 40))
        self.btn_play.setStyleSheet("QPushButton {\n"
"    background-color: #116530;   /* xanh lá đậm giống Save Account */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 8px 20px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1DB954;   /* xanh Spotify sáng hơn khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0b4520;   /* xanh lá tối hơn khi nhấn */\n"
"}")
        self.btn_play.setObjectName("btn_play")
        self.horizontalLayout.addWidget(self.btn_play)
        self.btn_add = QtWidgets.QPushButton(parent=SongItem)
        self.btn_add.setMinimumSize(QtCore.QSize(60, 40))
        self.btn_add.setStyleSheet("QPushButton {\n"
"    background-color: #116530;   /* xanh lá đậm giống Save Account */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 8px 20px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1DB954;   /* xanh Spotify sáng hơn khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0b4520;   /* xanh lá tối hơn khi nhấn */\n"
"}")
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout.addWidget(self.btn_add)

        self.retranslateUi(SongItem)
        QtCore.QMetaObject.connectSlotsByName(SongItem)

    def retranslateUi(self, SongItem):
        _translate = QtCore.QCoreApplication.translate
        SongItem.setWindowTitle(_translate("SongItem", "Song Item"))
        self.lbl_name.setText(_translate("SongItem", "Song Name"))
        self.lbl_artist.setText(_translate("SongItem", "Artist"))
        self.btn_play.setText(_translate("SongItem", "Play"))
        self.btn_add.setText(_translate("SongItem", "Add"))
